
name: Run JMeter Assignment

on:
  push:
    branches:
      - main
    paths:
      - '**/*.jmx'
  workflow_dispatch:
    inputs:
      jmx_file:
        description: 'Path to the JMX file to run'
        required: true
        default: './Parameterization_blazedemo.jmx'

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Find changed JMX files (push)
        if: github.event_name == 'push'
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '\.jmx$' || true)
          echo "CHANGED=$CHANGED" >> $GITHUB_ENV

      
      - name: Show changed JMX files (push)
        if: github.event_name == 'push'
        run: echo "Changed JMX files:$CHANGED"

     
      - name: Run JMeter on changed files (push)
        if: github.event_name == 'push' && env.CHANGED != ''
        run: |
          mkdir -p results
          for jmx in $CHANGED; do
            echo "Running JMeter: $jmx"
            docker run --rm -v $PWD:/mnt blazemeter/jmeter -n -t /mnt/$jmx -l /mnt/results/$(basename $jmx .jmx).jtl
          done

     
      - name: Run specified JMeter file (manual)
        if: github.event_name == 'workflow_dispatch'
        run: |
          mkdir -p results
          JMX_FILE="${{ github.event.inputs.jmx_file }}"
          echo "Manual run: Running JMeter for $JMX_FILE"
          docker run --rm -v $PWD:/mnt blazemeter/jmeter -n -t /mnt/$JMX_FILE -l /mnt/results/$(basename $JMX_FILE .jmx).jtl
