
name: Run JMeter Assignment

on:
  push:
    branches:
      - main
    paths:
      - '**/*.jmx'
  workflow_dispatch:

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find all JMX files
        run: |
          echo "CHANGED=$(find . -type f -name '*.jmx' | xargs)" >> $GITHUB_ENV

      - name: Show JMX files to run
        run: echo "Files:$CHANGED"

      - name: Run JMeter on appropriate JMX files
        if: env.CHANGED != ''
        run: |
          mkdir -p results
          for jmx in $CHANGED; do
            echo "Running JMeter: $jmx"
            docker run --rm -v $PWD:/mnt justb4/jmeter -n -t /mnt/$jmx -l /mnt/results/$(basename $jmx .jmx).jtl
          done
